# Generated by Django 2.0 on 2018-02-13 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pt', '0001_initial'), ('pt', '0002_auto_20171226_1036'), ('pt', '0003_remove_entry_date_updated'), ('pt', '0004_entry_date_updated'), ('pt', '0005_auto_20171227_1309'), ('pt', '0006_auto_20171228_0804'), ('pt', '0007_entry_trend'), ('pt', '0008_entry_prices'), ('pt', '0009_entry_owner'), ('pt', '0010_auto_20180105_1508'), ('pt', '0011_auto_20180105_1511'), ('pt', '0012_auto_20180106_1032')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('trend', models.CharField(choices=[('UP', '+'), ('DOWN', '-')], max_length=4, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt.Entry')),
            ],
            options={
                'verbose_name_plural': 'prices',
            },
        ),
    ]
