# Generated by Django 2.0 on 2017-12-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0002_auto_20171226_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_updated',
        ),
    ]
