# Generated by Django 2.0 on 2017-12-26 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0003_remove_entry_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
