# Generated by Django 2.0 on 2017-12-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0004_entry_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='url',
        ),
    ]
