# Generated by Django 2.0 on 2017-12-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0005_auto_20171227_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
