# Generated by Django 2.0 on 2017-12-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0006_auto_20171228_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='trend',
            field=models.CharField(choices=[('UP', '+'), ('DOWN', '-')], max_length=4, null=True),
        ),
    ]
