# Generated by Django 2.0 on 2017-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0007_entry_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prices',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
