# Generated by Django 2.0 on 2018-01-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0011_auto_20180105_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'prices',
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='price',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='prices',
        ),
        migrations.AddField(
            model_name='price',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt.Entry'),
        ),
    ]
